name: env_can
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python
  - ca-certificates
  - openssl
  - ipykernel
  - matplotlib
  - asammdf
prefix: C:\Users\ivanm\miniforge3\envs\env_can
